# Generated by Django 3.0.7 on 2020-06-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200625_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_cover_letter',
            field=models.TextField(),
        ),
    ]
