# Generated by Django 3.0.7 on 2020-07-02 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0003_auto_20200625_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='companies'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('salary', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('experience', models.TextField()),
                ('portfolio', models.TextField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='grade',
                                            to='job.Grade')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                related_name='specialty',
                                                to='job.Specialty')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='status',
                                             to='job.Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='user',
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
